---
- name: Collect Network Facts
  hosts: all
  vars_files:
    - secrets
  tasks:
    - name: Collect Facts from EOS
      arista.eos.eos_facts:
        gather_subset: all
    - name: Set and Cache Custom Fact
      ansible.builtin.set_fact:
        site: Egypt
        cacheable: yes
