---
- name: "DEMONSTRATE HOSTPIN STRATEGY"
  hosts: "all"
  gather_facts: False
  strategy: "host_pinned"
  serial: 2
  tasks:
    - name: "GET DEVICE NAMES"
      debug:
        msg: "{{ inventory_hostname }}"
    - name: "GET DEVICE OS"
      debug:
        msg: "{{ ansible_network_os }}"
