---
- name: "Test Custom Filter"
  hosts: "all"
  connection: "local"
  tasks:
    - name: "Read ACL data"
      ansible.builtin.include_vars: "ACLs.yml"
      run_once: yes
      delegate_to: "localhost"
    - name: "Apply Our Custom Filter"
      ansible.builtin.set_fact:
        standard_acl: "{{ ACLs | acl_state }}"
      run_once: yes
      delegate_to: "localhost"
    - name: "Display Output After Filter"
      ansible.builtin.debug: "var=standard_acl"
    - name: "Apply Our Custom Filter"
      set_fact:
        standard_acl: "{{ ACLs | acl_state }}"
        final_acl: "{{ ACLs | custom_acl('dport') }}"
      run_once: yes
    - name: "Display Output After Filter"
      debug: "var=final_acl"
