---
- name: "Validate Cache Data"
  connection: "local"
  hosts: "all"
  tasks:
    - name: "Validate all Interfaces"
      assert:
        that:
          - item.value.lineprotocol == "up"
      loop: "{{ ansible_net_interfaces | dict2items }}"
    - name: "Validate Custom Fact"
      assert:
        that:
          - site == 'Egypt'

