---
- name: "BUILD CONFIGS FOR NOKIA"
  hosts: "nokia_srlinux"
  connection: "local"
  roles:
    - "config_generation"
  vars_files:
    - srl_secret.yml
  tasks:
    - name: "DEPLOY ADVANCED CONFIG"
      nokia.srlinux.config:
        update:
          - path: /
            value: "{{ lookup('ansible.builtin.template', '{{playbook_dir}}/templates/srlinux.j2') }}"
