---
- name: "Configure Hostname and DNS"
  hosts: "nokia_srlinux"
  vars_files:
    - srl_secret.yml
  tasks:
    - name: "Configure the Hostname on Nokia"
      nokia.srlinux.config:
        replace:
          - path: /system/name/host-name
            value: "{{ inventory_hostname }}"
          - path: /system/dns/server-list
            value: "{{ global['dns'] }}"
        save_when: "changed"
