- name: Delete all VPC resources
  hosts: all
  gather_facts: no
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key_id }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:
    - name: Get VPC facts
      aws.amazon.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_facts

    - name: Extract VPC ID
      set_fact:
        vpc_id: "{{ vpc_facts.vpcs[0].id }}"

    - name: Start Delete VPC Resources
      block:
        - name: Delete Subnets
          aws.amazon.ec2_vpc_subnet:
            cidr: "{{ item.value.cidr }}"
            vpc_id: "{{ vpc_id }}"
            state: absent
          with_dict: "{{ vpc_subnets }}"

        - name: Delete NACLs
          aws.amazon.ec2_vpc_nacl:
            name: "{{ item.name }}"
            vpc_id: "{{ vpc_id }}"
            state: absent
          loop: "{{ network_acls }}"

        - name: Delete IGW
          aws.amazon.ec2_vpc_igw:
            vpc_id: "{{ vpc_id }}"
            state: absent

        - name: Delete VPC
          aws.amazon.ec2_vpc_net:
            cidr_block: "{{ vpc_cidr }}"
            name: "{{ vpc_name }}"
            state: absent
      when: vpc_id is defined
