---
interfaces:
  Ethernet1:
    ip_address: "172.31.1.1/31"
    description: "LEAF-TO-SPINE-CEOS-01-Ethernet3"
  Ethernet2:
    vlan: 10
    description: "LEAF-TO-CLIENT2-Eth1"
  Loopback0:
    ip_address: "10.100.1.1/32"
    description: "LOOPBACK FOR ROUTER ID"  
  Management0:
    ip_address: "198.51.100.12/24"
    description: "clab mgmt network"
bgp:
  asn: 65001
  peer_groups:
    underlay:
      - peer: ceos-01
        ip_address: 172.31.1.0
        remote_as: 65100
    overlay:
      - peer: ceos-01
        ip_address: 10.100.1.254
        remote_as: 65100

