---
interfaces:
  Ethernet1:
    ip_address: "172.31.1.4/31"
    description: "SPINE-TO-CORE-CRPD-01-ETHERNET2"
  Ethernet2:
    ip_address: "172.31.1.6/31"
    description: "SPINE-TO-CORE-CRPD-02-ETHERNET2"
  Ethernet3:
    ip_address: "172.31.1.0/31"
    description: "SPINE-TO-LEAF-CEOS-02-ETHERNET1"
  Ethernet4:
    ip_address: "172.31.1.2/31"
    description: "SPINE-TO-LEAF-CEOS-03-ETHERNET1"
  Loopback0:
    ip_address: "10.100.1.254/32"
    description: "LOOPBACK FOR ROUTER ID"  
  Management0:
    ip_address: "198.51.100.11/24"
    description: "clab mgmt network"
bgp:
  asn: 65100
  peer_groups:
    underlay:
      - peer: ceos-02
        ip_address: 172.31.1.1
        remote_as: 65001
      - peer: ceos-03
        ip_address: 172.31.1.3
        remote_as: 65002
    overlay:
      - peer: ceos-02
        ip_address: 10.100.1.1
        remote_as: 65001
      - peer: ceos-03
        ip_address: 10.100.1.2
        remote_as: 65002
    core:
      - peer: crpd-01
        ip_address: 172.31.1.5
        remote_as: 65400
      - peer: crpd-02
        ip_address: 172.31.1.7
        remote_as: 65400