---
- name: "Configure Hostname and DNS"
  hosts: arista_ceos
  tasks:
    - name: "Configure Basic Configuration on Arista Fabric"
      arista.eos.eos_system:
        hostname: "{{ inventory_hostname }}"
        name_servers: "{{ global['dns'] }}"
        state: present
