---
nautobot_url: http://127.0.0.1:8080
nautobot_token: 47a72c0b6b7a9c70c07501625a77fd398de59d1c

locations:
  - name: DC1
    description: "Main Data Center in Sydney"
    address: Sydney
    location_type: "datacenter"
  - name: DC2
    description: "Main Data Center in KSA"
    address: Riyadh
    location_type: "datacenter"

device_kinds:
  - role:
      name: Leaf_Switch
      color: 'f44336'  # red
    type:
      model: 7020SR
      vendor: Arista

  - role:
      name: Spine_Switch
      color: '2196f3'  # blue
    type:
      model: 7050CX3
      ru: 2
      vendor: Arista

p2p_ip:
  dc1-leaf01:
    - {port: Ethernet8, ip: 172.30.1.1/31 , peer: dc1-spine01, pport: Ethernet1, peer_ip: 172.30.1.0/31}
    - {port: Ethernet9, ip: 172.30.1.5/31 , peer: dc1-spine02, pport: Ethernet1, peer_ip: 172.30.1.4/31}
  dc1-leaf02:
    - {port: Ethernet8, ip: 172.30.1.3/31 , peer: dc1-spine01, pport: Ethernet2, peer_ip: 172.30.1.2/31}
    - {port: Ethernet9, ip: 172.30.1.7/31 , peer: dc1-spine02, pport: Ethernet2, peer_ip: 172.30.1.6/31}
  dc1-spine01:
    - {port: Ethernet1, ip: 172.30.1.0/31 , peer: dc1-leaf01, pport: Ethernet8, peer_ip: 172.30.1.1/31}
    - {port: Ethernet2, ip: 172.30.1.2/31 , peer: dc1-leaf02, pport: Ethernet8, peer_ip: 172.30.1.3/31}
    - {port: Ethernet6, ip: 172.30.1.8/31 , peer: dc1-spine02, pport: Ethernet6, peer_ip: 172.30.1.9/31}
  dc1-spine02:
    - {port: Ethernet1, ip: 172.30.1.4/31 , peer: dc1-leaf01, pport: Ethernet9, peer_ip: 172.30.1.5/31}
    - {port: Ethernet2, ip: 172.30.1.6/31 , peer: dc1-leaf02, pport: Ethernet9, peer_ip: 172.30.1.7/31}
    - {port: Ethernet6, ip: 172.30.1.9/31 , peer: dc1-spine01, pport: Ethernet6, peer_ip: 172.30.1.8/31}
  dc2-leaf01:
    - {port: Ethernet8, ip: 172.31.1.1/31 , peer: dc2-spine01, pport: Ethernet1, peer_ip: 172.31.1.0/31}
    - {port: Ethernet9, ip: 172.31.1.5/31 , peer: dc2-spine02, pport: Ethernet1, peer_ip: 172.31.1.4/31}
  dc2-leaf02:
    - {port: Ethernet8, ip: 172.31.1.3/31 , peer: dc2-spine01, pport: Ethernet2, peer_ip: 172.31.1.2/31}
    - {port: Ethernet9, ip: 172.31.1.7/31 , peer: dc2-spine02, pport: Ethernet2, peer_ip: 172.31.1.6/31}
  dc2-spine01:
    - {port: Ethernet1, ip: 172.31.1.0/31 , peer: dc2-leaf01, pport: Ethernet8, peer_ip: 172.31.1.1/31}
    - {port: Ethernet2, ip: 172.31.1.2/31 , peer: dc2-leaf02, pport: Ethernet8, peer_ip: 172.31.1.3/31}
    - {port: Ethernet6, ip: 172.31.1.8/31 , peer: dc2-spine02, pport: Ethernet6, peer_ip: 172.31.1.9/31}
  dc2-spine02:
    - {port: Ethernet1, ip: 172.31.1.4/31 , peer: dc2-leaf01, pport: Ethernet9, peer_ip: 172.31.1.5/31}
    - {port: Ethernet2, ip: 172.31.1.6/31 , peer: dc2-leaf02, pport: Ethernet9, peer_ip: 172.31.1.7/31}
    - {port: Ethernet6, ip: 172.31.1.9/31 , peer: dc2-spine01, pport: Ethernet6, peer_ip: 172.31.1.8/31}

subnets:
  - prefix: 172.30.1.0/24
    location: dc1
  - prefix: 172.31.1.0/24
    location: dc2
  - prefix: 10.100.1.0/24
    location: dc1
  - prefix: 10.100.2.0/24
    location: dc2
  - prefix: 172.20.1.0/24
    location: dc1
  - prefix: 172.20.2.0/24
    location: dc2
