---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
additional_build_steps:
  prepend_final:
    - ENV ANSIBLE_COLLECTIONS_PATHS="/usr/share/ansible/collections:/home/runner/.ansible/collections"
    - ENV ANSIBLE_HOME="/runner"
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.12
  ansible_runner:
    package_pip: ansible-runner
  python:
    - pynautobot
    - ansible-rulebook
    - asyncio
    - aiohttp
  system:
    - java-17 [platform:rpm]
    - gcc [platform:rpm]
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
  galaxy:
    collections:
      - name: networktocode.nautobot
      - name: community.general
      - name: ansible.utils
      - name: ansible.eda
      - name: arista.eos
