---
- name: Validate Azure Network Infrastructure
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Get Resource Group Facts
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ resource_group_name }}"
      register: azure_resourcegroups

    - name: Validate Resource Group is Deployed
      ansible.builtin.assert:
        that:
          - rg.name == resource_group_name
          - rg.properties.provisioning_state == 'Succeeded'
          - rg.location == region
      loop: "{{ azure_resourcegroups.resourcegroups }}"
      loop_control:
        loop_var: rg

    - name: Get Virtual Network Facts
      azure.azcollection.azure_rm_virtualnetwork_info:
        resource_group: "{{ resource_group_name }}"
      register: azure_virtualnetworks

    - name: Validate Virtual Networks are Deployed
      ansible.builtin.assert:
        that:
          - vnet.name == vnet_name
          - vnet.provisioning_state == 'Succeeded'
          - vnet.address_prefixes | length == 1
          - vnet.address_prefixes[0] == vnet_cidr
      loop: "{{ azure_virtualnetworks.virtualnetworks }}"
      loop_control:
        loop_var: vnet
