---
- name: Build GCP Environment
  hosts: all
  connection: local
  gather_facts: no
  force_handlers: True
  vars_files:
    - gcp_account_info.yml

  tasks:
    - name: Read the Vault Encrypted JSON File
      ansible.builtin.copy:
        content: "{{ lookup('file','gcp-ansible-secret.json') }}"
        dest: "{{ service_account_file }}"
      notify: Clean tmp Decrypted Files

    - name: Build GCP Network
      ansible.builtin.import_role:
        name: gcp_net_build

    - name: Build VM Instances
      ansible.builtin.include_role:
        name: gcp_vm_build
      loop: "{{ compute_nodes }}"
      loop_control:
        loop_var: node

    - name: Create the Route
      google.cloud.gcp_compute_route:
        name: "{{ route.name }}"
        description: "{{ route.description | default(omit) }}"
        dest_range: "{{ route.dest}}"
        network: "{{ gcp_vpc }}"
        next_hop_ip: "{{ route.nh }}"
        tags: "{{ route.apply_to.split(',') | default(omit) }}"
        state: present
        auth_kind: "{{ auth_kind }}"
        project: "{{ project }}"
        service_account_file: "{{ service_account_file }}"
      loop: "{{ custom_routes }}"
      loop_control:
        loop_var: route
      when:
      - custom_routes is defined
      - route.nh is defined

  handlers:
    - name: Clean tmp Decrypted Files
      ansible.builtin.file:
        path: "{{ service_account_file }}"
        state: absent
