---
- name: Validate GCP Network Environment
  hosts: all
  connection: local
  gather_facts: no
  force_handlers: True
  vars_files:
    - gcp_account_info.yml

  tasks:
    - name: Read the Vault Encrypted JSON File
      ansible.builtin.copy:
        content: "{{ lookup('file','gcp-ansible-secret.json') }}"
        dest: "{{ service_account_file }}"
      notify: Clean tmp Decrypted Files

    - name: Get Subnet Facts
      google.cloud.gcp_compute_subnetwork_info:
        region: "{{ region }}"
        auth_kind: "{{ auth_kind }}"
        project: "{{ project }}"
        service_account_file: "{{ service_account_file }}"
      loop: "{{ subnets }}"
      register: gcp_vpc_subnets

    # - debug: var=gcp_vpc_subnets

    - name: Validate all Subnets are Deployed
      ansible.builtin.assert:
        that:
          - gcp_vpc_subnets.results |
            selectattr('item.cidr','==',item.cidr) |
            map(attribute='item') |
            list
      loop: "{{ subnets }}"

  handlers:
    - name: Clean tmp Decrypted Files
      ansible.builtin.file:
        path: "{{ service_account_file }}"
        state: absent
