# ch2_pb1.yml
---
- name: Initial Playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: Display Hostname
      ansible.builtin.debug:
        msg: "Router name is {{ inventory_hostname }}"
    - name: Display the NTP Variables
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} has NTP servers {{ ntp }}"
