
- name: Create cloud providers (Manufacturers) within Nautobot
  networktocode.nautobot.manufacturer:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    name: "{{ group_names | difference(['cloud']) | first }}"
  throttle: 1

- name: Create cloud account within Nautobot
  networktocode.nautobot.cloud_account:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    name: "{{ group_names | difference(['cloud']) | first }} development account"
    provider: "{{ group_names | difference(['cloud']) | first }}"
    account_number: "{{ account_id }}"
  throttle: 1

- name: Create cloud network resource type within Nautobot
  networktocode.nautobot.cloud_resource_type:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    name: "{{ group_names | difference(['cloud']) | first }} network"
    provider: "{{ group_names | difference(['cloud']) | first }}"
    content_types:
      - "cloud.cloudnetwork"
  throttle: 1

- name: Create cloud subnet resource type within Nautobot
  networktocode.nautobot.cloud_resource_type:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    name: "{{ group_names | difference(['cloud']) | first }} subnet"
    provider: "{{ group_names | difference(['cloud']) | first }}"
    content_types:
      - "cloud.cloudnetwork"
  throttle: 1

- name: Create cloud networks within Nautobot
  networktocode.nautobot.cloud_network:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    name: "{{ inventory_hostname }} network"
    cloud_resource_type: "{{ group_names | difference(['cloud']) | first }} network"
    cloud_account: "{{ account_id }}"

- name: Create cloud subnets within Nautobot
  networktocode.nautobot.cloud_network:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    name: "{{ inventory_hostname }} subnet {{ item }}"
    cloud_resource_type: "{{ group_names | difference(['cloud']) | first }} subnet"
    cloud_account: "{{ account_id }}"
    parent: "{{ inventory_hostname }} network"
  loop:
    - a
    - b
    - c

- name: Create Cloud IP Prefixes for networks within Nautobot
  networktocode.nautobot.prefix:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    prefix: "{{ prefix }}"
    status: "Active"

- name: Create a cloud networks to prefix assignment
  networktocode.nautobot.cloud_network_prefix_assignment:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    cloud_network: "{{ inventory_hostname }} network"
    cloud_prefix: "{{ prefix }}"

- name: Calculate all subnets within the prefix
  ansible.builtin.set_fact:
    subnets: "{{ query('calculate_subnets', prefix, 26) }}"

- name: Create Cloud IP Prefixes for subnets within Nautobot
  networktocode.nautobot.prefix:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    prefix: "{{ item.0 }}"
    status: "Active"
  loop: "{{ subnets | zip(['a', 'b', 'c']) | list }}"
  register: subnet_prefixes

- name: Create a cloud subnets to prefix assignment
  networktocode.nautobot.cloud_network_prefix_assignment:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    state: "{{ nautobot_state }}"
    cloud_network: "{{ inventory_hostname }} subnet {{ item.item[1] }}"
    cloud_prefix:  "{{ item.prefix }}"
  loop: "{{ subnet_prefixes['results'] }}"
