---
- name: Create Nautobot Datacenter data
  import_tasks: create_datacenter.yml
  when: "'cloud' not in group_names"
  tags:
    - datacenter

- name: Create Nautobot Cloud data
  import_tasks: create_cloud.yml
  when: "'cloud' in group_names"
  tags:
    - cloud
