---
- name: Show Inventory
  hosts: "{{ lookup('ansible.builtin.env', 'DO_DROPLET_NAME') }}"
  gather_facts: false
  tasks:
    - name: Show SSH command
      ansible.builtin.debug:
        msg: "ssh -o StrictHostKeyChecking=no -i {{ lookup('ansible.builtin.env', 'SSH_KEY_PATH') }} root@{{ ansible_host }}"
